export const GET_ALL_FOOD_TYPES_REQUEST = "GET_ALL_FOOD_TYPES_REQUEST";
export const GET_ALL_FOOD_TYPES_SUCCESS = "GET_ALL_FOOD_TYPES_SUCCESS";
export const GET_ALL_FOOD_TYPES_FAILURE = "GET_ALL_FOOD_TYPES_FAILURE";

export const GET_FOOD_TYPE_REQUEST = "GET_FOOD_TYPE_REQUEST";
export const GET_FOOD_TYPE_SUCCESS = "GET_FOOD_TYPE_SUCCESS";
export const GET_FOOD_TYPE_FAILURE = "GET_FOOD_TYPE_FAILURE";

export const CREATE_FOOD_TYPE_REQUEST = "CREATE_FOOD_TYPE_REQUEST";
export const CREATE_FOOD_TYPE_SUCCESS = "CREATE_FOOD_TYPE_SUCCESS";
export const CREATE_FOOD_TYPE_FAILURE = "CREATE_FOOD_TYPE_FAILURE";

export const UPDATE_FOOD_TYPE_REQUEST = "UPDATE_FOOD_TYPE_REQUEST";
export const UPDATE_FOOD_TYPE_SUCCESS = "UPDATE_FOOD_TYPE_SUCCESS";
export const UPDATE_FOOD_TYPE_FAILURE = "UPDATE_FOOD_TYPE_FAILURE";

export const DELETE_FOOD_TYPE_REQUEST = "DELETE_FOOD_TYPE_REQUEST";
export const DELETE_FOOD_TYPE_SUCCESS = "DELETE_FOOD_TYPE_SUCCESS";
export const DELETE_FOOD_TYPE_FAILURE = "DELETE_FOOD_TYPE_FAILURE";
