export const GET_ALL_STATISTICS_REQUEST = "GET_ALL_STATISTICS_REQUEST";
export const GET_ALL_STATISTICS_SUCCESS = "GET_ALL_STATISTICS_SUCCESS";
export const GET_ALL_STATISTICS_FAILURE = "GET_ALL_STATISTICS_FAILURE";

export const GET_STATISTICS_REQUEST = "GET_STATISTICS_REQUEST";
export const GET_STATISTICS_SUCCESS = "GET_STATISTICS_SUCCES";
export const GET_STATISTICS_FAILURE = "GET_STATISTICS_FAILURE";

